// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VolleyLeague.Repositories;

#nullable disable

namespace VolleyLeague.Repositories.Migrations
{
    [DbContext(typeof(VolleyballContext))]
    [Migration("20240801133938_AddDataADCForScheduleData")]
    partial class AddDataADCForScheduleData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("tomasz1_voladmin")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CredentialsRole", b =>
                {
                    b.Property<int>("CredentialsId")
                        .HasColumnType("int");

                    b.Property<int>("RolesRoleId")
                        .HasColumnType("int");

                    b.HasKey("CredentialsId", "RolesRoleId");

                    b.HasIndex("RolesRoleId");

                    b.ToTable("CredentialsRole", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.AdminDefinedCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("ModifiedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("AdminDefinedCodes", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Articles", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Comment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CommentLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ContentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CommentLocationId");

                    b.ToTable("Comments", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.CommentLocation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CommentLocations", "tomasz1_voladmin");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Article"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Team"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Player"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Match"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Thread"
                        },
                        new
                        {
                            Id = 6,
                            Name = "PrivateMessage"
                        });
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Credentials", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Credentials", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.ForumCategory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("ForumCategories", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.ForumTopic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AuthorId")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("IsActive")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.HasIndex("CategoryId");

                    b.ToTable("ForumTopics", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Invitation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId");

                    b.HasIndex("UserId");

                    b.ToTable("Invitations", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.League", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Leagues", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Log", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Admin")
                        .HasColumnType("bit");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Link")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Logs", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Match", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("GuestTeamId")
                        .HasColumnType("int");

                    b.Property<int>("HomeTeamId")
                        .HasColumnType("int");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<string>("MatchInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MatchLeague")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MvpId")
                        .HasColumnType("int");

                    b.Property<int?>("RefereeId")
                        .HasColumnType("int");

                    b.Property<int>("RoundId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Schedule")
                        .HasColumnType("datetime2");

                    b.Property<byte>("Sector")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set1Team1Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set1Team2Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set2Team1Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set2Team2Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set3Team1Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set3Team2Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set4Team1Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set4Team2Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set5Team1Score")
                        .HasColumnType("tinyint");

                    b.Property<byte?>("Set5Team2Score")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Team1Score")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Team2Score")
                        .HasColumnType("tinyint");

                    b.Property<string>("UnknownRefereeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VenueId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GuestTeamId");

                    b.HasIndex("HomeTeamId");

                    b.HasIndex("LeagueId");

                    b.HasIndex("MvpId");

                    b.HasIndex("RefereeId");

                    b.HasIndex("RoundId");

                    b.HasIndex("VenueId");

                    b.ToTable("Matches", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.PersonalLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("LogId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LogId");

                    b.HasIndex("UserId");

                    b.ToTable("PersonalLogs", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Position", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Positions", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles", "tomasz1_voladmin");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Player"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Arbiter"
                        },
                        new
                        {
                            RoleId = 3,
                            Name = "Admin"
                        });
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Round", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.ToTable("Rounds", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Seasons", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.SportsVenue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdditionalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SportsVenues", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Team", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Accepted")
                        .HasColumnType("bit");

                    b.Property<int>("CaptainId")
                        .HasColumnType("int");

                    b.Property<int>("ChangeCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Image")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("ImageHeight")
                        .HasColumnType("int");

                    b.Property<int?>("ImageWidth")
                        .HasColumnType("int");

                    b.Property<bool?>("IsReportedToPlay")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValueSql("((1))");

                    b.Property<int>("LeagueId")
                        .HasColumnType("int");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("LogoHeight")
                        .HasColumnType("int");

                    b.Property<int?>("LogoWidth")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PointCorrection")
                        .HasColumnType("int");

                    b.Property<string>("TeamDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CaptainId")
                        .IsUnique();

                    b.HasIndex("LeagueId");

                    b.ToTable("Teams", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.TeamImage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<byte[]>("Image")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("ImageType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TeamId")
                        .IsUnique();

                    b.ToTable("TeamImage", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.TeamPlayer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("JoinDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("TeamId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("TeamId");

                    b.ToTable("TeamPlayers", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.TypedResult", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatchId")
                        .HasColumnType("int");

                    b.Property<byte>("Score1")
                        .HasColumnType("tinyint");

                    b.Property<byte>("Score2")
                        .HasColumnType("tinyint");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatchId");

                    b.HasIndex("UserId");

                    b.ToTable("TypedResults", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid?>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AdditionalEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("AttackRange")
                        .HasColumnType("int");

                    b.Property<int?>("BirthYear")
                        .HasColumnType("int");

                    b.Property<int?>("BlockRange")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<byte?>("Height")
                        .HasColumnType("tinyint");

                    b.Property<string>("Hobby")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("JerseyNumber")
                        .HasColumnType("tinyint");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PersonalInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Photo")
                        .HasColumnType("varbinary(max)");

                    b.Property<int?>("PhotoHeight")
                        .HasColumnType("int");

                    b.Property<int?>("PhotoWidth")
                        .HasColumnType("int");

                    b.Property<int>("PositionId")
                        .HasColumnType("int");

                    b.Property<string>("VolleyballIdol")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte?>("Weight")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("PositionId");

                    b.ToTable("Users", "tomasz1_voladmin");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.UserRegistrationVerificationCode", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ExpirationTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VerificationCodes", "tomasz1_voladmin");
                });

            modelBuilder.Entity("CredentialsRole", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Credentials", null)
                        .WithMany()
                        .HasForeignKey("CredentialsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Article", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.User", "Author")
                        .WithMany("Articles")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Comment", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.User", "Author")
                        .WithMany("Comments")
                        .HasForeignKey("AuthorId")
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.CommentLocation", "CommentLocation")
                        .WithMany("Comments")
                        .HasForeignKey("CommentLocationId")
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("CommentLocation");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Credentials", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.User", "User")
                        .WithOne("Credentials")
                        .HasForeignKey("VolleyLeague.Entities.Models.Credentials", "UserId")
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.ForumTopic", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.User", "Author")
                        .WithMany("Topics")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.ForumCategory", "Category")
                        .WithMany("Topics")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Invitation", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Team", "Team")
                        .WithMany("Invitations")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.User", "User")
                        .WithMany("Invitations")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Team");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Match", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Team", "GuestTeam")
                        .WithMany("GuestMatches")
                        .HasForeignKey("GuestTeamId")
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.Team", "HomeTeam")
                        .WithMany("HomeMatches")
                        .HasForeignKey("HomeTeamId")
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.League", "League")
                        .WithMany("Matches")
                        .HasForeignKey("LeagueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.User", "Mvp")
                        .WithMany("MVPMatches")
                        .HasForeignKey("MvpId");

                    b.HasOne("VolleyLeague.Entities.Models.User", "Referee")
                        .WithMany("RefereeMatches")
                        .HasForeignKey("RefereeId");

                    b.HasOne("VolleyLeague.Entities.Models.Round", "Round")
                        .WithMany("Matches")
                        .HasForeignKey("RoundId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.SportsVenue", "Venue")
                        .WithMany("Matches")
                        .HasForeignKey("VenueId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GuestTeam");

                    b.Navigation("HomeTeam");

                    b.Navigation("League");

                    b.Navigation("Mvp");

                    b.Navigation("Referee");

                    b.Navigation("Round");

                    b.Navigation("Venue");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.PersonalLog", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Log", "Log")
                        .WithMany("PersonalLogs")
                        .HasForeignKey("LogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.User", "User")
                        .WithMany("PersonalLogs")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Log");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Round", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Season", "Season")
                        .WithMany("Rounds")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.Navigation("Season");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Team", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.User", "Captain")
                        .WithOne("Team")
                        .HasForeignKey("VolleyLeague.Entities.Models.Team", "CaptainId")
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.League", "League")
                        .WithMany("Teams")
                        .HasForeignKey("LeagueId")
                        .IsRequired();

                    b.Navigation("Captain");

                    b.Navigation("League");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.TeamImage", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Team", "Team")
                        .WithOne("TeamImage")
                        .HasForeignKey("VolleyLeague.Entities.Models.TeamImage", "TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.TeamPlayer", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.User", "Player")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.Team", "Team")
                        .WithMany("TeamPlayers")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Player");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.TypedResult", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Match", "Match")
                        .WithMany("TypedResults")
                        .HasForeignKey("MatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VolleyLeague.Entities.Models.User", "User")
                        .WithMany("TypedResults")
                        .HasForeignKey("UserId")
                        .IsRequired();

                    b.Navigation("Match");

                    b.Navigation("User");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.User", b =>
                {
                    b.HasOne("VolleyLeague.Entities.Models.Position", "Position")
                        .WithMany("Users")
                        .HasForeignKey("PositionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Position");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.CommentLocation", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.ForumCategory", b =>
                {
                    b.Navigation("Topics");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.League", b =>
                {
                    b.Navigation("Matches");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Log", b =>
                {
                    b.Navigation("PersonalLogs");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Match", b =>
                {
                    b.Navigation("TypedResults");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Position", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Round", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Season", b =>
                {
                    b.Navigation("Rounds");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.SportsVenue", b =>
                {
                    b.Navigation("Matches");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.Team", b =>
                {
                    b.Navigation("GuestMatches");

                    b.Navigation("HomeMatches");

                    b.Navigation("Invitations");

                    b.Navigation("TeamImage");

                    b.Navigation("TeamPlayers");
                });

            modelBuilder.Entity("VolleyLeague.Entities.Models.User", b =>
                {
                    b.Navigation("Articles");

                    b.Navigation("Comments");

                    b.Navigation("Credentials");

                    b.Navigation("Invitations");

                    b.Navigation("MVPMatches");

                    b.Navigation("PersonalLogs");

                    b.Navigation("RefereeMatches");

                    b.Navigation("Team");

                    b.Navigation("TeamPlayers");

                    b.Navigation("Topics");

                    b.Navigation("TypedResults");
                });
#pragma warning restore 612, 618
        }
    }
}
